### ISSUE TITLE
SignUp and Login Pages

### ISSUE THREAD

**Issue by nickoliasxii** [markkazanski/flavasave#21]
- [x] Format Sign up page
- [x] Sign up page push user info to db
- [x] Check db for unique email/username during sign up
- [x] Format Login page
- [x] User Authentication
- [x] User Authorization
- [x] Path Routes

**Comment by JQuinnie** [comment]
- [ ] Format Sign up and Login pages
- [ ] User Authentication
- [ ] User Authorization
- [ ] Path Routes

**Comment by nickoliasxii** [comment]
Resolved by #61
