### ISSUE TITLE
NavLogged and FooterLogged becomes obselete

### ISSUE THREAD

**Issue by JQuinnie** [markkazanski/flavasave#62]
With the use of conditional rendering in Nav.js, separate logged in navbars (NavLogged and FooterLogged) are no longer needed by use of `isAuthenticated`

- [ ] Removal of NavLogged from all files
- [ ] Removal of FooterLogged from all files
- [ ] Clean up CSS with rendering

**Comment by nickoliasxii** [comment]
Keeping them now
